version: '2'
services:
  web:
    restart: unless-stopped
    build:
      context: .
      args:
        - HPC_USER
    working_dir: /code
    entrypoint: /code/docker-entrypoint.sh
    volumes:
      - /usr/share/nginx/html/static:/srv/static
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - ./:/code
      - /usr/share/nginx/html/uploads/:/srv/uploads
    ports:
      - "8000:8000"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - DJANGO_SETTINGS_MODULE=AraGenoSite.settings.prod
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - ADMINS=${ADMINS}
  hpc:
    restart: unless-stopped
    build:
      context: .
      args:
        - HPC_USER
    working_dir: /code
    command: ./manage.py listen_job_queue '${BROKER}'
    volumes:
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - ./:/code
      - /usr/share/nginx/html/uploads/:/srv/uploads
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - DJANGO_SETTINGS_MODULE=AraGenoSite.settings.prod
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - ADMINS=${ADMINS}

