version: '3'
services:
  web:
    restart: unless-stopped
    image: "docker.artifactory.imp.ac.at/the1001genomes/arageno:latest"
    volumes:
      - /usr/share/nginx/html/static:/srv/static
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - /usr/share/nginx/html/uploads/:/srv/uploads
      - /srv/arageno/logs:/srv/logs
    ports:
      - "8000:8000"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - HPC_HOST=${HPC_HOST}
      - HPC_USER=${HPC_USER}
      - DJANGO_SETTINGS_MODULE=AraGenoSite.settings.prod
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - ADMINS=${ADMINS}

