# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 16:09
from __future__ import unicode_literals

import arageno.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('num_of_samples', models.PositiveIntegerField()),
                ('num_of_markers', models.PositiveIntegerField()),
                ('pubmed_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('runtime_identify', models.CharField(max_length=100)),
                ('memory_identify', models.CharField(max_length=100)),
                ('runtime_crosses', models.CharField(max_length=100)),
                ('memory_crosses', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GenotypeSubmission',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(-1, b'Error'), (0, b'Created'), (1, b'Queued'), (2, b'Processing'), (3, b'Finished')], db_index=True, default=0)),
                ('statistics', models.TextField(blank=True, db_column=b'data', null=True)),
                ('_progress', models.PositiveSmallIntegerField(db_column=b'progress', default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('genotype_file', models.FileField(upload_to=arageno.models.genotype_file_directory)),
                ('_num_of_markers', models.PositiveIntegerField(blank=True, db_column=b'num_of_markers', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentifyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(-1, b'Error'), (0, b'Created'), (1, b'Queued'), (2, b'Processing'), (3, b'Finished')], db_index=True, default=0)),
                ('statistics', models.TextField(blank=True, db_column=b'data', null=True)),
                ('_progress', models.PositiveSmallIntegerField(db_column=b'progress', default=0)),
                ('identify_file', models.FileField(upload_to=b'')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CrossesJob',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(-1, b'Error'), (0, b'Created'), (1, b'Queued'), (2, b'Processing'), (3, b'Finished')], db_index=True, default=0)),
                ('statistics', models.TextField(blank=True, db_column=b'data', null=True)),
                ('_progress', models.PositiveSmallIntegerField(db_column=b'progress', default=0)),
                ('identifyjob', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='arageno.IdentifyJob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='identifyjob',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arageno.Dataset'),
        ),
        migrations.AddField(
            model_name='identifyjob',
            name='genotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arageno.GenotypeSubmission'),
        ),
    ]
