# Generated by Django 2.2.6 on 2019-10-15 19:42

import arageno.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('num_of_samples', models.PositiveIntegerField()),
                ('num_of_markers', models.PositiveIntegerField()),
                ('pubmed_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('runtime_identify', models.CharField(max_length=100)),
                ('memory_identify', models.CharField(max_length=100)),
                ('runtime_crosses', models.CharField(max_length=100)),
                ('memory_crosses', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GenotypeSubmission',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(-1, 'Error'), (0, 'Created'), (1, 'Queued'), (2, 'Processing'), (3, 'Finished')], db_index=True, default=0)),
                ('statistics', models.TextField(blank=True, db_column='data', null=True)),
                ('_progress', models.PositiveSmallIntegerField(db_column='progress', default=0)),
                ('jobid', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('genotype_file', models.FileField(upload_to=arageno.models.genotype_file_directory)),
                ('_num_of_markers', models.PositiveIntegerField(blank=True, db_column='num_of_markers', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentifyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(-1, 'Error'), (0, 'Created'), (1, 'Queued'), (2, 'Processing'), (3, 'Finished')], db_index=True, default=0)),
                ('statistics', models.TextField(blank=True, db_column='data', null=True)),
                ('_progress', models.PositiveSmallIntegerField(db_column='progress', default=0)),
                ('jobid', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('identify_file', models.FileField(upload_to=arageno.models.identify_result_file)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arageno.Dataset')),
                ('genotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arageno.GenotypeSubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CrossesJob',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(-1, 'Error'), (0, 'Created'), (1, 'Queued'), (2, 'Processing'), (3, 'Finished')], db_index=True, default=0)),
                ('statistics', models.TextField(blank=True, db_column='data', null=True)),
                ('_progress', models.PositiveSmallIntegerField(db_column='progress', default=0)),
                ('jobid', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('identifyjob', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='arageno.IdentifyJob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
